"""add description to onboarding tasks

Revision ID: 1759c8e0eb35
Revises: d8984cd48594
Create Date: 2026-08-19 20:18:41.795072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1759c8e0eb35'
down_revision: Union[str, Sequence[str], None] = 'd8984cd48594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_tasks', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_tasks', 'description')
    # ### end Alembic commands ###
