"""complete team model

Revision ID: 1d22af6b6f1c
Revises: d4c7e27be5c8
Create Date: 2026-08-18 19:51:57.381336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d22af6b6f1c'
down_revision: Union[str, Sequence[str], None] = 'd4c7e27be5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'team_manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'team_manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
