"""add employee_id to meetings

Revision ID: 36e44fb3f99b
Revises: b8cc5acce62d
Create Date: 2026-08-20 13:17:57.501335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e44fb3f99b'
down_revision: Union[str, Sequence[str], None] = 'b8cc5acce62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meetings', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'employee_id')
    # ### end Alembic commands ###
