"""add unique constraint to meeting participants

Revision ID: 45ead6602108
Revises: fb55e6333695
Create Date: 2026-08-19 15:22:25.186306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ead6602108'
down_revision: Union[str, Sequence[str], None] = 'fb55e6333695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_meeting_participant', 'meeting_participants', ['meeting_id', 'employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_meeting_participant', 'meeting_participants', type_='unique')
    # ### end Alembic commands ###
