"""add competency cycles

Revision ID: 56fe91eb5444
Revises: 8c9660e94cb5
Create Date: 2026-08-20 15:04:42.132669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fe91eb5444'
down_revision: Union[str, Sequence[str], None] = '8c9660e94cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CLOSED', name='competencycyclestatus'), nullable=False),
    sa.Column('phase', sa.Enum('RATING', 'DEVELOPMENT', 'REVIEW', name='competencycyclephase'), nullable=False),
    sa.Column('meeting_notes', sa.String(), nullable=True),
    sa.Column('meeting_completed', sa.Boolean(), nullable=False),
    sa.Column('focus_ends_at', sa.DateTime(), nullable=True),
    sa.Column('review_started_at', sa.DateTime(), nullable=True),
    sa.Column('review_started_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['review_started_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_cycles_id'), 'competency_cycles', ['id'], unique=False)
    op.create_table('competency_cycle_competencies',
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['competency_cycles.id'], ),
    sa.PrimaryKeyConstraint('cycle_id', 'competency_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competency_cycle_competencies')
    op.drop_index(op.f('ix_competency_cycles_id'), table_name='competency_cycles')
    op.drop_table('competency_cycles')
    # ### end Alembic commands ###
