"""add development plan item

Revision ID: 7cb27eba5d26
Revises: 09b5fa8dc339
Create Date: 2026-08-21 00:38:07.974842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb27eba5d26'
down_revision: Union[str, Sequence[str], None] = '09b5fa8dc339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('development_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_role', sa.Enum('EMPLOYEE', 'MANAGER', 'HRBP', 'HR_MANAGER', name='employeeroletype'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['competency_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('development_plan_items')
    # ### end Alembic commands ###
