"""add onboarding feedback table

Revision ID: 98065fdedc86
Revises: df64f5ff2371
Create Date: 2026-08-19 20:49:38.604124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98065fdedc86'
down_revision: Union[str, Sequence[str], None] = 'df64f5ff2371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['onboarding_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('onboarding_feedbacks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], name=op.f('onboarding_feedbacks_created_by_fkey')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('onboarding_feedbacks_employee_id_fkey')),
    sa.ForeignKeyConstraint(['phase_id'], ['onboarding_phases.id'], name=op.f('onboarding_feedbacks_phase_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_feedbacks_pkey'))
    )
    op.drop_table('onboarding_feedback')
    # ### end Alembic commands ###
