"""update meeting_participant

Revision ID: a707317ff35d
Revises: 676a00a8686f
Create Date: 2026-08-20 14:11:08.255671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a707317ff35d'
down_revision: Union[str, Sequence[str], None] = '676a00a8686f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_participants', sa.Column('all_required_participants_present', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_participants', 'all_required_participants_present')
    # ### end Alembic commands ###
