"""make competency cycle end date nullable

Revision ID: a970c41cf14c
Revises: 52658719508b
Create Date: 2026-08-20 16:25:31.530730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a970c41cf14c'
down_revision: Union[str, Sequence[str], None] = '52658719508b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TYPE competencycyclestatus "
        "ADD VALUE IF NOT EXISTS 'SELF_ASSESSMENT_PENDING'"
    )

    op.execute(
        "ALTER TYPE competencycyclestatus "
        "ADD VALUE IF NOT EXISTS 'MANAGER_ASSESSMENT_PENDING'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
