"""initial schema

Revision ID: ae3f6e99ff6a
Revises: 
Create Date: 2026-08-18 12:42:28.972109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3f6e99ff6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team_manager_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('monthly_salary', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXITED', name='employeestatus'), nullable=False),
    sa.Column('exit_type', sa.Enum('RESIGNATION', 'TERMINATION', name='exittype'), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key(
        "fk_team_manager",
        "teams",
        "employees",
        ["team_manager_id"],
        ["id"]
    )
    op.create_table('employee_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hrbp_team_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hrbp_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hrbp_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hrbp_id', 'team_id', name='uq_hrbp_team')
    )
    op.create_table('onboardings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('buddy_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'FINAL_DECISION_PENDING', 'COMPLETED', 'EXITED', 'CANCELLED', name='onboardingstatus'), nullable=False),
    sa.Column('current_phase_number', sa.Integer(), nullable=True),
    sa.Column('employee_decision', sa.Enum('CONTINUE', 'EXIT', name='decision'), nullable=True),
    sa.Column('manager_decision', sa.Enum('CONTINUE', 'EXIT', name='decision'), nullable=True),
    sa.Column('final_result', sa.Enum('PENDING', 'CONTINUE', 'EXIT', name='finalresult'), nullable=False),
    sa.Column('investment_decision', sa.Enum('NONE', 'INVESTMENT', 'NORMAL', name='investmentdecision'), nullable=False),
    sa.ForeignKeyConstraint(['buddy_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider_id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('onboarding_id', sa.Integer(), nullable=True),
    sa.Column('onboarding_month', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'HELD', 'CANCELLED', name='meetingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboardings.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onboarding_id', sa.Integer(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='phasestatus'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboardings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['onboarding_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_tasks')
    op.drop_table('onboarding_phases')
    op.drop_table('meetings')
    op.drop_table('users')
    op.drop_table('onboardings')
    op.drop_table('hrbp_team_assignments')
    op.drop_table('employee_role')
    op.drop_table('teams')
    op.drop_table('positions')
    op.drop_table('employees')
    # ### end Alembic commands ###
