"""add notes to meetings

Revision ID: b8cc5acce62d
Revises: cfc17ccefcea
Create Date: 2026-08-20 11:23:08.628672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cc5acce62d'
down_revision: Union[str, Sequence[str], None] = 'cfc17ccefcea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'notes')
    # ### end Alembic commands ###
