"""adding competency mangaement

Revision ID: c97a91d76dfc
Revises: 65b2e7871cf8
Create Date: 2026-08-20 22:57:43.807001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97a91d76dfc'
down_revision: Union[str, Sequence[str], None] = '65b2e7871cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency_manager_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['competency_cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'competency_id', name='uq_cycle_competency_manager_assessment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competency_manager_assessments')
    # ### end Alembic commands ###
