"""sync with model changes (position fields, etc)

Revision ID: ce0f510afed1
Revises: 8911f1098c45
Create Date: 2026-08-22 13:31:45.590241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0f510afed1'
down_revision: Union[str, Sequence[str], None] = '8911f1098c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('job_description', sa.String(), nullable=True))
    op.add_column('positions', sa.Column('default_onboarding_duration_months', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'default_onboarding_duration_months')
    op.drop_column('positions', 'job_description')
    # ### end Alembic commands ###
