"""rename onboarding feedback created_by

Revision ID: cfc17ccefcea
Revises: 1e7619d64586
Create Date: 2026-08-19 21:29:06.506095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc17ccefcea'
down_revision: Union[str, Sequence[str], None] = '1e7619d64586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_feedback', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('onboarding_feedback_created_by_fkey'), 'onboarding_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_feedback', 'employees', ['created_by_id'], ['id'])
    op.drop_column('onboarding_feedback', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_feedback', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'onboarding_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('onboarding_feedback_created_by_fkey'), 'onboarding_feedback', 'employees', ['created_by'], ['id'])
    op.drop_column('onboarding_feedback', 'created_by_id')
    # ### end Alembic commands ###
