"""adding department and changing teams and employee

Revision ID: d4c7e27be5c8
Revises: 6d6ee34365ea
Create Date: 2026-08-18 19:39:53.573890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c7e27be5c8'
down_revision: Union[str, Sequence[str], None] = '6d6ee34365ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('teams', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'department_id')
    op.drop_table('departments')
    # ### end Alembic commands ###
