"""add development plans table

Revision ID: d8984cd48594
Revises: 45ead6602108
Create Date: 2026-08-19 19:27:13.517917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8984cd48594'
down_revision: Union[str, Sequence[str], None] = '45ead6602108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('development_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onboarding_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.String(), nullable=False),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('training', sa.String(), nullable=False),
    sa.Column('mentoring', sa.String(), nullable=False),
    sa.Column('next_steps', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboardings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('development_plans')
    # ### end Alembic commands ###
