"""make competency cycle end date nullable

Revision ID: dacff0b6eda5
Revises: 56fe91eb5444
Create Date: 2026-08-20 15:35:11.484656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacff0b6eda5'
down_revision: Union[str, Sequence[str], None] = '56fe91eb5444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competency_cycles', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competency_cycles', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
