"""add created_at to onboarding feedback

Revision ID: e500f1a92503
Revises: 98065fdedc86
Create Date: 2026-08-19 20:51:47.923241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e500f1a92503'
down_revision: Union[str, Sequence[str], None] = '98065fdedc86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_feedback', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_feedback', 'created_at')
    # ### end Alembic commands ###
