"""make participant meeting

Revision ID: fb55e6333695
Revises: 98ac14b0c028
Create Date: 2026-08-19 15:05:41.814041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb55e6333695'
down_revision: Union[str, Sequence[str], None] = '98ac14b0c028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='meetingresponsestatus'), nullable=False),
    sa.Column('held_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('meetings_participant_id_fkey'), 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'participant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('meetings_participant_id_fkey'), 'meetings', 'employees', ['participant_id'], ['id'])
    op.drop_table('meeting_participants')
    # ### end Alembic commands ###
